import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme, Container, Flex, Section, Link as RadixLink } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme appearance="light" accentColor="blue" grayColor="slate" radius="large">
          <Section size="1">
            <Container size="3">
              <Flex direction="column" gap="5">
                {children}
                <footer>
                  <RadixLink href="/">Shipping Dashboard</RadixLink>
                </footer>
              </Flex>
            </Container>
          </Section>
        </Theme>
      </body>
    </html>
  );
}
